'use client'

import { Download } from 'lucide-react'
import type { DriftZone } from '@/lib/database.types'
import type { FallbackCard } from '@/lib/fallback-cards'

interface Props {
  projectName: string
  score: number
  analyzedAt: string
  zones: DriftZone[]
  cards: FallbackCard[]
  summary: string
}

export default function ExportButton({ projectName, score, analyzedAt, zones, cards, summary }: Props) {
  function download() {
    const riskOrder: Record<string, number> = { ghost: 0, overbuilt: 1, misunderstood: 2, underbuilt: 3 }
    const risks = [...zones]
      .filter(z => z.drift_type !== 'aligned')
      .sort((a, b) => (riskOrder[a.drift_type] ?? 9) - (riskOrder[b.drift_type] ?? 9))
      .slice(0, 3)
    const ghosts = zones.filter(z => z.drift_type === 'ghost')

    const lines = [
      `# Drift Report: ${projectName}`,
      ``,
      `**Drift Score:** ${score}/100`,
      `**Last Analyzed:** ${new Date(analyzedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
      ``,
      `---`,
      ``,
      `## 01 — Top Risks`,
      ``,
      ...risks.map(z => [
        `### ${z.feature_name} (${z.drift_type})`,
        `- Priority: ${z.intended_priority}`,
        `- Usage: ${z.actual_usage_score}/100`,
        ``,
      ]).flat(),
      `## 02 — Ghost Features`,
      ``,
      ghosts.length === 0
        ? `No ghost features detected.`
        : ghosts.map(z => `⚠ **${z.feature_name}** — Built as ${z.intended_priority} priority. ${z.actual_usage_score}/100 usage.`).join('\n'),
      ``,
      `## 03 — AI Recommendations`,
      ``,
      ...cards.map(c => [
        `### ${c.title} [${c.priority.toUpperCase()}]`,
        `> ${c.user_story}`,
        ``,
        `**Copy:** ${c.copy_rewrite}`,
        `**Mockup:** ${c.mockup_suggestion}`,
        ``,
      ]).flat(),
      `## 04 — Founder Summary`,
      ``,
      `> ${summary}`,
      ``,
      `---`,
      `*Generated by DRIFT — powered by Novus.ai*`,
    ]

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
    const url  = URL.createObjectURL(blob)
    const a    = Object.assign(document.createElement('a'), {
      href:     url,
      download: `drift-report-${projectName.toLowerCase().replace(/\s+/g, '-')}.md`,
    })
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <button
      onClick={download}
      className="flex items-center gap-2 rounded-xl border border-slate-700/80 bg-slate-900/60 px-6 py-3 text-sm font-semibold text-slate-300 backdrop-blur-sm transition-all hover:border-slate-500 hover:text-white"
    >
      <Download className="h-4 w-4" />
      Export as Markdown
    </button>
  )
}
